# ==========================================================
# bootstrap-profile.ps1
# Wires the machine's PowerShell profile to ultra-profile.
# Run once per machine (as the user, no admin required).
#
# What it does:
#   1. Clones ultra-profile from GitHub if not already present locally
#   2. Locates (or creates) $PROFILE.CurrentUserAllHosts (profile.ps1)
#   3. Writes a thin loader that dot-sources ultra-profile/profile.ps1
#   4. Persists $env:ULTRA_PROFILE as a user env var (Windows only)
#
# Usage - fresh machine (no OneDrive required):
#   iex (irm 'https://raw.githubusercontent.com/<your-org>/ultra-profile/main/bootstrap-profile.ps1')
#
# Usage - local (already cloned):
#   pwsh ./bootstrap-profile.ps1
#   pwsh ./bootstrap-profile.ps1 -Force          # overwrite existing profile
#   pwsh ./bootstrap-profile.ps1 -WhatIf         # preview without changing anything
#
# Optional - override clone destination:
#   pwsh ./bootstrap-profile.ps1 -Destination ~/mytools/ultra-profile
# ==========================================================

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$Destination,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Test-IsWindows { return $IsWindows -or ($env:OS -eq 'Windows_NT') }

$repoUrl = 'https://github.com/<your-org>/ultra-profile.git'

# ---- Resolve ultra-profile root ----
if ($Destination) {
    $ultraRoot = $Destination
} elseif ($PSScriptRoot -and (Test-Path -LiteralPath (Join-Path $PSScriptRoot 'profile.ps1'))) {
    # Running from inside the cloned directory
    $ultraRoot = $PSScriptRoot
} else {
    # Default clone destination
    $ultraRoot = Join-Path ([Environment]::GetFolderPath('UserProfile')) 'foundry/ultra-profile'
}

# ---- Clone from GitHub if not present ----
if (-not (Test-Path -LiteralPath (Join-Path $ultraRoot 'profile.ps1'))) {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw 'git is required but not found. Install Git and retry.'
    }
    Write-Host ('ultra-profile not found at ' + $ultraRoot + ' - cloning from GitHub...') -ForegroundColor Yellow
    $parentDir = Split-Path $ultraRoot -Parent
    if (-not (Test-Path -LiteralPath $parentDir)) {
        New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
    }
    if ($PSCmdlet.ShouldProcess($ultraRoot, "git clone $repoUrl")) {
        git clone $repoUrl $ultraRoot
        Write-Host ('Cloned to: ' + $ultraRoot) -ForegroundColor Green
    }
}

$ultraProfile = Join-Path $ultraRoot 'profile.ps1'
if (-not (Test-Path -LiteralPath $ultraProfile)) {
    throw ('profile.ps1 not found at ' + $ultraRoot + '. Clone may have failed.')
}

# ---- Locate the machine profile path ----
$profilePath = $PROFILE.CurrentUserAllHosts  # ~/.config/powershell/profile.ps1 (all hosts)

$profileDir = Split-Path $profilePath -Parent
if (-not (Test-Path -LiteralPath $profileDir)) {
    if ($PSCmdlet.ShouldProcess($profileDir, 'Create directory')) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
        Write-Host ('Created profile directory: ' + $profileDir) -ForegroundColor Yellow
    }
}

# ---- Guard against overwriting a non-trivial existing profile ----
if ((Test-Path -LiteralPath $profilePath) -and -not $Force) {
    $existing = Get-Content -LiteralPath $profilePath -Raw -ErrorAction SilentlyContinue
    if ($existing -and $existing.Trim()) {
        Write-Warning ('Profile already exists at ' + $profilePath + '.')
        Write-Warning 'Use -Force to overwrite, or manually inspect and merge.'
        Write-Host ''
        Write-Host 'Existing content:' -ForegroundColor DarkGray
        Write-Host $existing -ForegroundColor DarkGray
        return
    }
}

# ---- Build loader content ----
$escapedPath = $ultraRoot -replace "'", "''"
$loaderContent = @"
# Auto-generated by bootstrap-profile.ps1 - do not edit manually.
# To update, re-run bootstrap-profile.ps1 from the ultra-profile directory.

`$_ultraRoot = if (`$env:ULTRA_PROFILE) { `$env:ULTRA_PROFILE } else { '$escapedPath' }
`$_ultraProfile = Join-Path `$_ultraRoot 'profile.ps1'

if (Test-Path -LiteralPath `$_ultraProfile) {
    . `$_ultraProfile
} else {
    Write-Warning ('ultra-profile not found at ' + `$_ultraRoot + '. Re-run bootstrap-profile.ps1.')
}

Remove-Variable _ultraRoot, _ultraProfile -ErrorAction SilentlyContinue
"@

# ---- Write the profile ----
if ($PSCmdlet.ShouldProcess($profilePath, 'Write loader profile')) {
    $loaderContent | Out-File -FilePath $profilePath -Encoding utf8 -NoNewline
    Write-Host ('Profile written to: ' + $profilePath) -ForegroundColor Green
}

# ---- Windows: persist ULTRA_PROFILE as a user env var ----
if (Test-IsWindows) {
    if ($PSCmdlet.ShouldProcess('ULTRA_PROFILE (user env var)', "Set to '$ultraRoot'")) {
        [System.Environment]::SetEnvironmentVariable('ULTRA_PROFILE', $ultraRoot, 'User')
        Write-Host ('Set user env var ULTRA_PROFILE = ' + $ultraRoot) -ForegroundColor Green
        Write-Host '(Takes effect in new sessions - current session uses the embedded path.)' -ForegroundColor DarkGray
    }
}

Write-Host ''
Write-Host 'Bootstrap complete. Start a new PowerShell session to verify.' -ForegroundColor Green
Write-Host ('Profile path : ' + $profilePath) -ForegroundColor Cyan
Write-Host ('ultra-profile: ' + $ultraRoot) -ForegroundColor Cyan
